/*
 * @lc app=leetcode id=389 lang=cpp
 *
 * [389] Find the Difference
 *
 * https://leetcode.com/problems/find-the-difference/description/
 *
 * algorithms
 * Easy (53.34%)
 * Likes:    529
 * Dislikes: 233
 * Total Accepted:    151K
 * Total Submissions: 282.8K
 * Testcase Example:  '"abcd"\n"abcde"'
 *
 * 
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * Example:
 * 
 * Input:
 * s = "abcd"
 * t = "abcde"
 * 
 * Output:
 * e
 * 
 * Explanation:
 * 'e' is the letter that was added.
 * 
 */
class Solution {
public:
    char findTheDifference(string s, string t) {
        int counter[26];
        memset(counter, 0, sizeof(counter));

        for (char ch : s) {
            counter[ch - 'a']++;
        }

        for (char ch : t) {
            counter[ch - 'a']--;
        }

        for (int i = 0; i < 26; ++i) {
            if (counter[i] == -1) {
                return 'a' + i;
            }
        }

        return ' ';
    }
};
